# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  testProject: '**/*Test/*.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building for $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Testing for $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Packaging (Publishing) for $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/SimpleAPI/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts'
